import React, { useMemo, useState, useEffect, useRef } from "react";
import {
  Menu,
  MessageCircle,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Sparkles,
  PlayCircle,
  Clock,
  Image as ImageIcon,
  Video as VideoIcon,
  Filter,
  SlidersHorizontal,
  ThumbsUp,
  Eye,
  X,
  ArrowLeft,
  ArrowRight,
  Maximize,
  Share2,
  Link,
  Check,
} from "lucide-react";

// Helper to generate recent timestamps
const minutesAgo = (mins) => {
  const d = new Date();
  d.setMinutes(d.getMinutes() - mins);
  return d.toISOString();
};

// Base mock items without the Concept Art tag


const getLiveStatusLabel = () => {
  const now = new Date();
  const hour = now.getHours();

  if (hour >= 10 && hour < 20) {
    const options = ["Just uploaded", "Updated 12 mins ago", "Updated 5 mins ago"];
    return options[now.getMinutes() % options.length];
  }

  const lastUpdate = new Date();
  lastUpdate.setHours(19, 55, 0, 0);
  const timeStr = lastUpdate.toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });

  return `Last updated today at ${timeStr}`;
};

const formatRelativeTime = (isoString) => {
  const now = new Date();
  const then = new Date(isoString);
  const diffMs = now - then;
  const diffMins = Math.round(diffMs / 60000);

  if (diffMins < 60) return `${diffMins}m ago`;
  const diffHours = Math.round(diffMins / 60);
  if (diffHours < 24) return `${diffHours}h ago`;
  const diffDays = Math.round(diffHours / 24);
  return `${diffDays}d ago`;
};

const getISTDate = () => {
  const now = new Date();
  const istOffsetMinutes = 330; // UTC+5:30
  const utcMillis = now.getTime() + now.getTimezoneOffset() * 60000;
  return new Date(utcMillis + istOffsetMinutes * 60000);
};

const isActiveHour = () => {
  const hourIST = getISTDate().getHours();
  return hourIST >= 10 && hourIST < 20;
};

const typeLabelMap = {
  post: "Post",
  story: "Story",
  reel: "Reel",
};

const AI_CONCEPTS = [
  {
    title: "AI Concept: Futuristic UI Grid",
    subtitle: "Autogenerated layout explorations for product drops.",
    category: "AI Concepts",
    imageUrl:
      "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80",
    layout: "static",
  },
  {
    title: "AI Concept: Neon Campaign",
    subtitle: "Speculative visuals for a bold launch sprint.",
    category: "AI Concepts",
    imageUrl:
      "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80",
    layout: "carousel",
  },
  {
    title: "AI Concept: Story Stack",
    subtitle: "9:16 story-ready frames with CTA space baked in.",
    category: "AI Stories",
    imageUrl:
      "https://images.unsplash.com/photo-1529333166433-0f3c0c4c30b5?auto=format&fit=crop&w=900&q=80",
    layout: "story",
  },
];

const generateAiItem = () => {
  const concept = AI_CONCEPTS[Math.floor(Math.random() * AI_CONCEPTS.length)];
  const nowIso = new Date().toISOString();
  const base = {
    id: Date.now() + Math.floor(Math.random() * 1000),
    type: concept.layout === "story" ? "story" : "post",
    category: concept.category,
    title: concept.title,
    subtitle: concept.subtitle,
    imageUrl: concept.imageUrl,
    videoUrl: undefined,
    layout: concept.layout === "story" ? "story" : concept.layout,
    createdAt: nowIso,
    likes: Math.floor(Math.random() * 50) + 20,
    views: Math.floor(Math.random() * 200) + 60,
    isConceptArt: true,
  };
  if (base.layout === "carousel") {
    base.slides = [concept.imageUrl, concept.imageUrl];
  }
  return base;
};

// Normalize media URLs (e.g., Google Drive links -> direct download)
const normalizeMediaUrl = (url) => {
  if (!url) return url;
  try {
    const parsed = new URL(url);
    const host = parsed.hostname;
    const isDrive = host.includes("drive.google.com") || host.includes("docs.google.com");
    if (isDrive) {
      const idFromQuery = parsed.searchParams.get("id");
      const idFromPath = parsed.pathname.split("/d/")[1]?.split("/")[0];
      const fileId = idFromQuery || idFromPath;
      if (fileId) {
        // Use lh3.googleusercontent.com for direct image embedding (avoids 302 redirects and 403 issues)
        return `https://lh3.googleusercontent.com/d/${fileId}`;
      }
    }
    return url;
  } catch {
    return url;
  }
};

function Header({ onToggleFilters, isFilterOpen, liveStatus }) {
  return (
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/80 shadow-sm shadow-slate-200/60 backdrop-blur">
      <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-900 text-sm font-semibold text-slate-50">
              DM
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-sm font-semibold tracking-tight text-slate-900">
                  Diviner Media
                </span>
                <span className="inline-flex items-center rounded-full bg-slate-900/5 px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.12em] text-slate-500">
                  Live Portfolio
                </span>
              </div>
              <p className="text-xs text-slate-500">
                Creative studio for high-converting social design.
              </p>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="hidden items-center gap-2 rounded-full border border-emerald-100 bg-emerald-50/80 px-3 py-1 text-xs text-emerald-700 sm:flex">
            <span className="relative flex h-3 w-3">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75" />
              <span className="relative inline-flex h-3 w-3 rounded-full bg-emerald-500" />
            </span>
            <span className="font-medium">Feed active</span>
            <span className="h-4 w-px bg-emerald-200" />
            <span className="flex items-center gap-1 text-[11px] text-emerald-700/80">
              <Clock className="h-3 w-3" /> {liveStatus}
            </span>
          </div>

          <a
            href="https://wa.me/918347572000"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-600 shadow-sm hover:border-slate-300 hover:bg-slate-50"
          >
            <MessageCircle className="h-3.5 w-3.5" />
            <span>Chat on WhatsApp</span>
          </a>

          <button
            type="button"
            className="ml-1 inline-flex items-center justify-center rounded-full border border-slate-200 bg-white p-2 text-slate-700 shadow-sm hover:bg-slate-100 lg:hidden"
            onClick={onToggleFilters}
          >
            <Menu className="h-4 w-4" />
          </button>
        </div>
      </div>

      {/* Mobile live status */}
      <div className="border-t border-slate-200 bg-white/90 sm:hidden">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-2 text-xs text-slate-600">
          <div className="flex items-center gap-1.5">
            <span className="relative flex h-2.5 w-2.5">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75" />
              <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-emerald-500" />
            </span>
            <span className="font-medium text-emerald-700">Feed active</span>
          </div>
          <span className="flex items-center gap-1 text-[11px] text-slate-500">
            <Clock className="h-3 w-3" />
            {liveStatus}
          </span>
        </div>

        {isFilterOpen && (
          <div className="border-t border-slate-200 bg-white px-4 py-2 text-xs text-slate-600 lg:hidden">
            <p className="text-[11px] text-slate-500">
              Use the filter below to view Posts, Stories, or Reels.
            </p>
          </div>
        )}
      </div>
    </header>
  );
}

function MasonryItemCard({ item, isLatest, liveStatus, onOpen, onRegisterView }) {
  const handleClick = () => {
    onRegisterView?.(item.id);
    onOpen?.(item);
  };

  const handleMouseEnter = () => {
    onRegisterView?.(item.id);
  };

  const handleImgError = (e) => {
    if (e.currentTarget.dataset.fallback) return;
    e.currentTarget.dataset.fallback = "true";
    e.currentTarget.src =
      "https://images.unsplash.com/photo-1529101091764-c3526daf38fe?auto=format&fit=crop&w=1200&q=80";
  };

  return (
    <article
      className="mb-4 break-inside-avoid cursor-pointer rounded-3xl border border-slate-200 bg-white shadow-md shadow-slate-200/60 transition hover:-translate-y-0.5 hover:shadow-lg"
      onClick={handleClick}
      onMouseEnter={handleMouseEnter}
    >
      <div className="relative overflow-hidden rounded-t-3xl bg-slate-100">
        {item.type === "story" ? (
          <div className="relative w-full aspect-[9/16] overflow-hidden bg-slate-100">
            <img
              src={normalizeMediaUrl(item.imageUrl)}
              alt={item.title}
              className="h-full w-full object-cover"
              loading="lazy"
              referrerPolicy="no-referrer"
              onError={handleImgError}
            />
            <div className="absolute inset-x-3 top-3 flex items-center justify-between">
              <span className="rounded-full bg-black/60 px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.16em] text-slate-50">
                Story Series
              </span>
              <span className="flex gap-0.5">
                <span className="h-0.5 w-5 rounded-full bg-slate-50/80" />
                <span className="h-0.5 w-5 rounded-full bg-slate-50/40" />
                <span className="h-0.5 w-5 rounded-full bg-slate-50/20" />
              </span>
            </div>
          </div>
        ) : (
          <div className="relative w-full overflow-hidden bg-slate-100">
            <img
              src={normalizeMediaUrl(item.imageUrl)}
              alt={item.title}
              className="w-full h-auto block"
              loading="lazy"
              referrerPolicy="no-referrer"
              onError={handleImgError}
            />
            {(item.layout === "carousel" || (item.slides && item.slides.length > 1)) && (
              <div className="absolute bottom-3 right-3 flex items-center gap-1 rounded-full bg-slate-900/80 px-2 py-1 text-[10px] font-medium text-slate-50">
                <ImageIcon className="h-3 w-3" />
                <span>Carousel preview</span>
              </div>
            )}
          </div>
        )}

        {isLatest && (
          <div className="absolute left-3 top-3 flex items-center gap-1 rounded-full bg-emerald-500 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-white shadow shadow-emerald-500/40">
            <span className="relative flex h-2 w-2">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-white/80 opacity-75" />
              <span className="relative inline-flex h-2 w-2 rounded-full bg-white" />
            </span>
            <span>Just in</span>
          </div>
        )}
      </div>

      <div className="space-y-2 px-3.5 py-3.5">
        <div className="flex items-start justify-between gap-2">
          <div>
            <div className="flex items-center gap-2">
              <span className="rounded-full bg-slate-900/5 px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.16em] text-slate-500">
                {item.category}
              </span>
              <span className="rounded-full bg-slate-900/5 px-2 py-0.5 text-[10px] font-medium text-slate-500">
                {typeLabelMap[item.type]}
              </span>
            </div>
            <h3 className="mt-1 text-sm font-semibold tracking-tight text-slate-900">
              {item.title}
            </h3>
          </div>
        </div>
        <p className="text-xs text-slate-500">{item.subtitle}</p>
        <div className="flex items-center justify-between pt-1 text-[11px] text-slate-400">
          <span className="flex items-center gap-1">
            <Clock className="h-3 w-3" />
            <span>{formatRelativeTime(item.createdAt)}</span>
          </span>

          <div className="flex items-center gap-3">
            <span className="flex items-center gap-1 text-[10px] font-medium text-slate-400">
              <Eye className="h-3 w-3" />
              {item.totalViews.toLocaleString()}
            </span>
            {isLatest ? (
              <span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-medium text-emerald-700">
                {liveStatus}
              </span>
            ) : item.isConceptArt ? (
              <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-500">
                AI Used
              </span>
            ) : null}
          </div>
        </div>
      </div>
    </article>
  );
}



function ReferralAnimation() {
  return (
    <div className="mt-4 flex h-12 items-center justify-center rounded-xl border border-slate-700/50 bg-slate-800/40 px-4 text-xs font-medium shadow-sm animate-float-ui transition-all duration-500">
      <div className="flex items-center gap-2">
        <span className="relative flex h-1.5 w-1.5">
          <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-indigo-400 opacity-75"></span>
          <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-indigo-500"></span>
        </span>
        <span className="text-slate-200">Refer our work if you liked it!</span>
      </div>
    </div>
  );
}

function ReelCard({ item, isLatest, onOpen, onRegisterView }) {
  const handleClick = () => {
    onRegisterView?.(item.id);
    onOpen?.(item);
  };

  const handleMouseEnter = () => {
    onRegisterView?.(item.id);
  };

  const coverSrc = normalizeMediaUrl(item.videoUrl || item.imageUrl);

  const handleImgError = (e) => {
    if (e.currentTarget.dataset.fallback) return;
    e.currentTarget.dataset.fallback = "true";
    e.currentTarget.src =
      "https://images.unsplash.com/photo-1526498460520-4c246339dccb?auto=format&fit=crop&w=1200&q=80";
  };

  return (
    <article
      className="flex cursor-pointer flex-col overflow-hidden rounded-3xl border border-slate-800/70 bg-slate-900/70 shadow-lg shadow-slate-900/60 backdrop-blur transition hover:-translate-y-0.5 hover:border-cyan-400/60 hover:shadow-cyan-500/40"
      onClick={handleClick}
      onMouseEnter={handleMouseEnter}
    >
      <div className="relative">
        <div className="aspect-[9/16] w-full overflow-hidden bg-slate-900">
          <img
            src={coverSrc}
            alt={item.title}
            className="h-full w-full object-cover"
            loading="lazy"
            referrerPolicy="no-referrer"
            onError={handleImgError}
          />
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="flex h-14 w-14 items-center justify-center rounded-full bg-black/60 backdrop-blur">
              <PlayCircle className="h-7 w-7 text-slate-50" />
            </div>
          </div>
          {isLatest && (
            <div className="absolute left-3 top-3 flex items-center gap-1 rounded-full bg-emerald-500 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-white">
              Live reel
            </div>
          )}
        </div>
      </div>
      <div className="space-y-1.5 px-3 py-3 text-slate-50">
        <div className="flex items-center justify-between gap-2">
          <div>
            <div className="flex items-center gap-1.5">
              <span className="rounded-full bg-slate-900/40 px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.16em] text-slate-200">
                {item.category}
              </span>
              <span className="inline-flex items-center gap-1 rounded-full bg-slate-900/40 px-2 py-0.5 text-[10px] text-slate-200">
                <VideoIcon className="h-3 w-3" /> Reel
              </span>
            </div>
            <h3 className="mt-1 line-clamp-2 text-sm font-semibold text-slate-50">
              {item.title}
            </h3>
          </div>
        </div>
        <p className="line-clamp-2 text-xs text-slate-300">{item.subtitle}</p>
        <div className="mt-2 flex items-center justify-between text-[11px] text-slate-300">
          <span className="flex items-center gap-1">
            <Clock className="h-3 w-3" /> {formatRelativeTime(item.createdAt)}
          </span>
          <div className="flex items-center gap-3">
            <span className="flex items-center gap-1 text-[10px] font-medium">
              <Eye className="h-3 w-3" />
              {item.totalViews.toLocaleString()}
            </span>
          </div>
        </div>
      </div>
    </article>
  );
}

function MobileFeedItem({ item, onOpen, onRegisterView }) {
  const isReel = item.type === "reel";
  const mediaAspectClass =
    item.type === "story"
      ? "w-full aspect-[9/16]"
      : item.layout === "carousel"
        ? ""
        : "";

  const handleClick = () => {
    onRegisterView?.(item.id);
    onOpen?.(item);
  };

  const handleMouseEnter = () => {
    onRegisterView?.(item.id);
  };

  const totalViews = item.totalViews ?? item.views ?? 0;
  const likes = item.likes ?? 0;
  const mediaSrc = isReel
    ? normalizeMediaUrl(item.videoUrl || item.imageUrl)
    : normalizeMediaUrl(item.imageUrl);
  const handleImgError = (e) => {
    if (e.currentTarget.dataset.fallback) return;
    e.currentTarget.dataset.fallback = "true";
    e.currentTarget.src =
      "https://images.unsplash.com/photo-1529101091764-c3526daf38fe?auto=format&fit=crop&w=1200&q=80";
  };

  return (
    <article
      className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-md shadow-slate-200/60 transition hover:-translate-y-0.5 hover:shadow-lg"
      onClick={handleClick}
      onMouseEnter={handleMouseEnter}
    >
      <div
        className={`relative overflow-hidden ${isReel ? "aspect-[9/16] w-full bg-slate-900" : `bg-slate-100 ${mediaAspectClass}`
          }`}
      >
        {isReel ? (
          <>
            <img
              src={mediaSrc}
              alt={item.title}
              className="h-full w-full object-cover"
              loading="lazy"
              referrerPolicy="no-referrer"
              onError={handleImgError}
            />
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-black/50 backdrop-blur">
                <PlayCircle className="h-7 w-7 text-slate-50" />
              </div>
            </div>
          </>
        ) : (
          <img
            src={mediaSrc}
            alt={item.title}
            className={item.type === "story" ? "h-full w-full object-cover" : "w-full h-auto block"}
            loading="lazy"
            referrerPolicy="no-referrer"
            onError={handleImgError}
          />
        )}
        <div className="absolute left-3 top-3 flex items-center gap-1 rounded-full bg-black/50 px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.16em] text-slate-50">
          <span className="flex items-center gap-1">
            {isReel ? <VideoIcon className="h-3 w-3" /> : <ImageIcon className="h-3 w-3" />}
            {typeLabelMap[item.type]}
          </span>
        </div>
      </div>
      <div className="space-y-1.5 px-3.5 py-3.5">
        <div className="flex items-center justify-between">
          <div className="flex flex-wrap items-center gap-1.5">
            <span className="rounded-full bg-slate-900/5 px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.16em] text-slate-500">
              {item.category}
            </span>
          </div>
          <span className="flex items-center gap-1 text-[11px] text-slate-400">
            <Clock className="h-3 w-3" /> {formatRelativeTime(item.createdAt)}
          </span>
        </div>
        <h3 className="text-sm font-semibold tracking-tight text-slate-900">
          {item.title}
        </h3>
        <p className="text-xs text-slate-500">{item.subtitle}</p>
        <div className="mt-1 flex flex-wrap items-center gap-3 text-[11px] text-slate-400">
          <span className="flex items-center gap-1">
            <ThumbsUp className="h-3 w-3" />
            <span>{likes.toLocaleString()} likes</span>
          </span>
          <span className="flex items-center gap-1">
            <Eye className="h-3 w-3" />
            <span>{totalViews.toLocaleString()} views</span>
          </span>
        </div>
      </div>
    </article>
  );
}

function FooterCTA() {
  return (
    <footer className="border-t border-slate-200 bg-gradient-to-r from-slate-900 via-slate-900 to-slate-950">
      <div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-8 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-xs font-medium uppercase tracking-[0.16em] text-slate-300">
            Let&apos;s add your brand to this feed
          </p>
          <p className="mt-1 max-w-md text-sm text-slate-300/90">
            Share a quick brief on WhatsApp or explore our microservices menu. We reply
            fast during working hours.
          </p>
        </div>

        <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
          <a
            href="https://wa.me/"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center justify-center gap-2 rounded-full bg-orange-500 px-4 py-2 text-sm font-semibold text-white shadow-sm shadow-orange-500/40 hover:bg-orange-600"
          >
            <MessageCircle className="h-4 w-4" />
            <span>Share your experience on WhatsApp</span>
          </a>

          <a
            href="/microservices"
            className="inline-flex items-center justify-center gap-1.5 rounded-full border border-slate-700 bg-slate-900 px-4 py-2 text-sm font-semibold text-slate-50 shadow-sm hover:bg-slate-800"
          >
            <span>View our services</span>
            <ChevronRight className="h-4 w-4" />
          </a>
        </div>
      </div>
    </footer>
  );
}

function FilterBar({
  topCategories,
  allCategories,
  activeCategory,
  onCategoryChange,
  showAllCategories,
  onToggleShowAll,
  timeFilter,
  onTimeFilterChange,
  sortMode,
  onSortModeChange,
}) {
  const timeOptions = [
    { value: "all", label: "All time" },
    { value: "1w", label: "1 week" },
    { value: "2w", label: "2 weeks" },
    { value: "3w", label: "3 weeks" },
    { value: "4w", label: "4 weeks" },
    { value: "1m", label: "1 month" },
  ];

  const sortOptions = [
    { value: "latest", label: "Latest updated" },
    { value: "views", label: "Most viewed" },
    { value: "best", label: "Best collection" },
  ];

  const renderCategoryPill = (category, key) => (
    <button
      key={key || category}
      type="button"
      onClick={() => onCategoryChange(category)}
      className={`inline-flex items-center gap-1 rounded-full border px-3 py-1 text-xs font-medium transition ${activeCategory === category
        ? "border-slate-900 bg-slate-900 text-slate-50"
        : "border-slate-200 bg-white text-slate-600 hover:border-slate-300 hover:bg-slate-50"
        }`}
    >
      {category === "all" && <Sparkles className="h-3 w-3" />}
      <span>{category === "all" ? "All categories" : category}</span>
    </button>
  );

  return (
    <section className="mb-4 mt-2 rounded-3xl border border-slate-200 bg-white/95 px-3.5 py-3.5 shadow-md shadow-slate-200/60">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-start gap-2">
          <div className="mt-0.5 rounded-full bg-slate-900/5 p-1.5">
            <Filter className="h-3.5 w-3.5 text-slate-600" />
          </div>
          <div>
            <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500">
              Live feed filters
            </p>
            <p className="text-xs text-slate-500">
              Tune what you see across posts, stories & reels in one go.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={onToggleShowAll}
          className="inline-flex items-center justify-center gap-1 rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 text-[11px] font-medium text-slate-600 hover:bg-slate-100"
        >
          <span>{showAllCategories ? "Collapse" : "See all"}</span>
          {showAllCategories ? (
            <ChevronUp className="h-3 w-3" />
          ) : (
            <ChevronDown className="h-3 w-3" />
          )}
        </button>
      </div>

      {/* Top categories row */}
      <div className="mt-3 flex flex-wrap gap-1.5">
        {renderCategoryPill("all", "all")}
        {topCategories.map((cat) => renderCategoryPill(cat))}
      </div>

      {/* Expanded categories + sort controls */}
      {showAllCategories && (
        <div className="mt-3 space-y-3 border-t border-slate-200 pt-3">
          <div className="flex flex-wrap gap-1.5">
            {allCategories.map((cat) =>
              topCategories.includes(cat) ? null : renderCategoryPill(cat)
            )}
          </div>

          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex flex-wrap items-center gap-1.5 text-[11px]">
              <span className="inline-flex items-center gap-1 rounded-full bg-slate-900/5 px-2 py-0.5 font-medium text-slate-600">
                <Clock className="h-3 w-3" />
                Duration
              </span>
              {timeOptions.map((opt) => (
                <button
                  key={opt.value}
                  type="button"
                  onClick={() => onTimeFilterChange(opt.value)}
                  className={`rounded-full px-2.5 py-0.5 text-[11px] font-medium transition ${timeFilter === opt.value
                    ? "bg-slate-900 text-slate-50"
                    : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                    }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>
        </div>
      )}
    </section>
  );
}

function ItemModal({ item, isLatest, liveStatus, onClose }) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [touchStartX, setTouchStartX] = useState(null);
  if (!item) return null;

  const isReel = item.type === "reel";
  const isVideo = !isReel && !!item.videoUrl;
  const isCarousel = item.layout === "carousel" || (item.slides && item.slides.length > 1);
  const isStory = item.type === "story";

  const slideCount = item.slides?.length || 1;

  const handlePrev = () => {
    if (slideCount <= 1) return;
    setCurrentSlide((prev) => (prev - 1 + slideCount) % slideCount);
  };

  const handleNext = () => {
    if (slideCount <= 1) return;
    setCurrentSlide((prev) => (prev + 1) % slideCount);
  };

  const handleTouchStart = (e) => {
    setTouchStartX(e.touches[0].clientX);
  };

  const handleTouchEnd = (e) => {
    if (touchStartX == null) return;
    const deltaX = e.changedTouches[0].clientX - touchStartX;
    if (Math.abs(deltaX) > 40) {
      if (deltaX < 0) handleNext();
      else handlePrev();
    }
    setTouchStartX(null);
  };

  const formattedExactTime = new Date(item.createdAt).toLocaleString([], {
    dateStyle: "medium",
    timeStyle: "short",
  });
  const mediaSrc = isReel
    ? normalizeMediaUrl(item.videoUrl || item.imageUrl)
    : normalizeMediaUrl(item.slides?.[currentSlide] || item.imageUrl);
  const handleImgError = (e) => {
    if (e.currentTarget.dataset.fallback) return;
    e.currentTarget.dataset.fallback = "true";
    e.currentTarget.src =
      "https://images.unsplash.com/photo-1526498460520-4c246339dccb?auto=format&fit=crop&w=1200&q=80";
  };
  const canSlide = slideCount > 1;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/80 px-3 py-6 sm:px-6"
      onClick={onClose}
    >
      <div
        className="flex w-full max-w-5xl max-h-[90vh] flex-col overflow-y-auto rounded-3xl border border-slate-700 bg-[#040817] text-slate-50 shadow-2xl shadow-slate-900/80"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-slate-800 px-4 py-3 sm:px-6">
          <div>
            <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">
              Creative Overview
            </p>
            <h2 className="text-sm font-semibold text-slate-50 sm:text-base">
              {item.title}
            </h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-slate-800 text-slate-200 hover:bg-slate-700"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
        <div className="flex flex-1 flex-col gap-4 overflow-hidden p-4 sm:flex-row sm:p-6">
          {/* Media area (left side of modal) */}
          {/* Media area */}
          <div className="flex-1 flex items-center justify-center">
            {isReel ? (
              <div
                className="relative aspect-[9/16] rounded-[32px] overflow-hidden bg-black shadow-xl"
                style={{ width: 'min(420px, 45vh)' }}
              >
                <iframe
                  src={item.videoUrl}
                  className="w-full h-full border-0"
                  allow="autoplay; fullscreen"
                  allowFullScreen
                  title={item.title || 'Reel video'}
                />
              </div>
            ) : isVideo ? (
              // Non-reel videos: keep a simple native <video>
              <div className="relative w-full max-w-[420px] rounded-[32px] overflow-hidden bg-black">
                <video
                  src={item.videoUrl}
                  className="w-full h-full object-contain"
                  controls
                />
              </div>
            ) : (
              // Existing image layout for static posts/stories
              <div className="relative w-full max-w-[420px] rounded-[32px] overflow-hidden bg-black">
                <img
                  src={mediaSrc}
                  alt={item.title || 'Design piece'}
                  className="w-full h-auto object-contain max-h-[80vh]"
                />
              </div>
            )}
          </div>
          {isStory && (
            <div className="pointer-events-none absolute inset-x-4 top-4 flex items-center justify-between">
              <div className="flex flex-1 gap-1">
                {Array.from({ length: slideCount }).map((_, idx) => (
                  <span
                    key={idx}
                    className={`h-0.5 flex-1 rounded-full ${idx <= currentSlide ? "bg-orange-400" : "bg-slate-600"
                      }`}
                  />
                ))}
              </div>
            </div>
          )}


          {/* Info area */}
          <aside className="flex w-full flex-col gap-3 rounded-2xl border border-slate-800 bg-slate-900/80 p-3 text-xs sm:w-72 sm:p-4">
            <div className="flex flex-wrap items-center gap-1.5">
              <span className="rounded-full bg-slate-800 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-200">
                {item.category}
              </span>
              <span className="rounded-full bg-slate-800 px-2 py-0.5 text-[10px] font-medium text-slate-300">
                {typeLabelMap[item.type]} • {item.layout}
              </span>
              {item.isConceptArt && (
                <span className="inline-flex items-center gap-1 rounded-full bg-violet-500/20 px-2 py-0.5 text-[10px] font-medium text-violet-100">
                  <Sparkles className="h-3 w-3" /> Concept art
                </span>
              )}
              {isLatest && (
                <span className="inline-flex items-center gap-1 rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-medium text-emerald-300">
                  <span className="relative flex h-2 w-2">
                    <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400/80 opacity-75" />
                    <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-400" />
                  </span>
                  Live in feed
                </span>
              )}
            </div>

            <div>
              <p className="text-[11px] uppercase tracking-[0.16em] text-slate-500">
                Snapshot
              </p>
              <p className="mt-1 text-xs text-slate-200">{item.subtitle}</p>
            </div>

            <div className="grid grid-cols-2 gap-2 rounded-xl bg-slate-900/80 p-2">
              <div className="space-y-0.5">
                <p className="text-[10px] text-slate-500">Created</p>
                <p className="text-[11px] font-medium text-slate-100">
                  {formattedExactTime}
                </p>
                <p className="text-[10px] text-slate-500">
                  {formatRelativeTime(item.createdAt)}
                </p>
              </div>
              <div className="space-y-0.5">
                <p className="text-[10px] text-slate-500">Engagement</p>
                <p className="text-[11px] text-slate-100">
                  <span className="inline-flex items-center gap-1">
                    <Eye className="h-3 w-3" /> {item.totalViews.toLocaleString()} views
                  </span>
                </p>
              </div>
            </div>

            <ReferralAnimation />

            <div className="mt-auto flex flex-col gap-2 pt-4">
              <a
                href={`https://wa.me/?text=${encodeURIComponent(`Check out this design: ${item.title}`)}`}
                target="_blank"
                rel="noreferrer"
                className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#25D366] px-4 py-2.5 text-xs font-semibold text-white transition hover:bg-[#20bd5a] active:scale-95"
              >
                <Share2 className="h-3.5 w-3.5" />
                Share on WhatsApp
              </a>
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(window.location.href);
                  const btn = document.getElementById('copy-btn-text');
                  if (btn) btn.innerText = 'Copied!';
                  setTimeout(() => { if (btn) btn.innerText = 'Copy Link'; }, 2000);
                }}
                className="flex w-full items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-800/50 px-4 py-2.5 text-xs font-semibold text-slate-300 transition hover:bg-slate-800 active:scale-95"
              >
                <Link className="h-3.5 w-3.5" />
                <span id="copy-btn-text">Copy Link</span>
              </button>
            </div>
          </aside>
        </div>
      </div>
    </div >
  );
}

function App() {
  const [activeMobileFilter, setActiveMobileFilter] = useState("all");
  const [isFilterOpen, setIsFilterOpen] = useState(false);

  const [feedItems, setFeedItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function loadFeed() {
      try {
        const res = await fetch("https://diviner-portfolio.vercel.app/api/portfolio-feed", {
          cache: "no-store",
        });
        const data = await res.json();

        if (Array.isArray(data.items) && data.items.length > 0) {
          // ✅ Use ONLY backend items
          setFeedItems(data.items);
        } else {
          // 🔁 Fallback only when API has nothing
          setFeedItems([]);
        }
      } catch (err) {
        console.error("Failed to load portfolio feed:", err);
        setFeedItems([]);
      } finally {
        setLoading(false);
      }
    }

    loadFeed();                      // initial load
    const interval = setInterval(loadFeed, 60 * 60 * 1000); // hourly refresh

    return () => clearInterval(interval);
  }, []);

  const [activeCategory, setActiveCategory] = useState("all");
  const [showAllCategories, setShowAllCategories] = useState(false);
  const [timeFilter, setTimeFilter] = useState("all");
  const [sortMode, setSortMode] = useState("latest");
  const [viewCounts, setViewCounts] = useState({});
  const [activeItem, setActiveItem] = useState(null);

  const registerView = (id) => {
    setViewCounts((prev) => ({
      ...prev,
      [id]: (prev[id] || 0) + 1,
    }));
  };





  const itemsWithViews = useMemo(
    () =>
      feedItems.map((item) => ({
        ...item,
        totalViews: viewCounts[item.id] ?? item.views ?? 0,
      })),
    [feedItems, viewCounts]
  );

  const latestItemId = useMemo(() => {
    if (!itemsWithViews.length) return null;
    return itemsWithViews.reduce((latest, current) =>
      new Date(current.createdAt) > new Date(latest.createdAt) ? current : latest
    ).id;
  }, [itemsWithViews]);

  const liveStatusLabel = useMemo(() => getLiveStatusLabel(), []);

  const { allCategories, topCategories } = useMemo(() => {
    const counts = {};
    itemsWithViews.forEach((item) => {
      counts[item.category] = (counts[item.category] || 0) + 1;
    });
    const allCategoriesArr = Object.keys(counts).sort();
    const topCategoriesArr = [...allCategoriesArr]
      .sort((a, b) => counts[b] - counts[a])
      .slice(0, 5);
    return { allCategories: allCategoriesArr, topCategories: topCategoriesArr };
  }, [itemsWithViews]);

  const filteredItems = useMemo(() => {
    let items = [...itemsWithViews];

    if (activeCategory !== "all") {
      items = items.filter((item) => item.category === activeCategory);
    }

    if (timeFilter !== "all") {
      const now = new Date();
      let daysBack = 0;
      if (timeFilter === "1w") daysBack = 7;
      else if (timeFilter === "2w") daysBack = 14;
      else if (timeFilter === "3w") daysBack = 21;
      else if (timeFilter === "4w") daysBack = 28;
      else if (timeFilter === "1m") daysBack = 30;

      if (daysBack > 0) {
        const threshold = new Date(now);
        threshold.setDate(now.getDate() - daysBack);
        items = items.filter((item) => new Date(item.createdAt) >= threshold);
      }
    }

    items = [...items].sort((a, b) => {
      if (sortMode === "latest") {
        return new Date(b.createdAt) - new Date(a.createdAt);
      }
      if (sortMode === "views") {
        const vA = a.totalViews || 0;
        const vB = b.totalViews || 0;
        if (vB !== vA) return vB - vA;
        return new Date(b.createdAt) - new Date(a.createdAt);
      }
      if (sortMode === "best") {
        const scoreA = (a.likes || 0) * 2 + (a.totalViews || 0);
        const scoreB = (b.likes || 0) * 2 + (b.totalViews || 0);
        if (scoreB !== scoreA) return scoreB - scoreA;
        return new Date(b.createdAt) - new Date(a.createdAt);
      }
      return 0;
    });

    return items;
  }, [itemsWithViews, activeCategory, timeFilter, sortMode]);

  const reels = useMemo(
    () => filteredItems.filter((item) => item.type === "reel"),
    [filteredItems]
  );

  const desktopMasonryItems = useMemo(
    () => filteredItems.filter((item) => item.type !== "reel"),
    [filteredItems]
  );

  const mobileFeedItems = useMemo(() => {
    let items = [...filteredItems];
    if (activeMobileFilter === "posts") items = items.filter((i) => i.type === "post");
    if (activeMobileFilter === "stories") items = items.filter((i) => i.type === "story");
    if (activeMobileFilter === "reels") items = items.filter((i) => i.type === "reel");
    return items;
  }, [filteredItems, activeMobileFilter]);

  return (
    <div
      className="flex min-h-screen flex-col text-slate-900
      bg-[#f8fafc]
      [background-image:radial-gradient(circle_at_1px_1px,#e2e8f0_1px,transparent_0)]
      [background-size:16px_16px]"
    >
      <Header
        onToggleFilters={() => setIsFilterOpen((prev) => !prev)}
        isFilterOpen={isFilterOpen}
        liveStatus={liveStatusLabel}
      />

      <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col px-4 pb-10 pt-4 lg:pt-6">
        <div className="flex flex-col gap-3">
          <FilterBar
            topCategories={topCategories}
            allCategories={allCategories}
            activeCategory={activeCategory}
            onCategoryChange={setActiveCategory}
            showAllCategories={showAllCategories}
            onToggleShowAll={() => setShowAllCategories((prev) => !prev)}
            timeFilter={timeFilter}
            onTimeFilterChange={setTimeFilter}
            sortMode={sortMode}
            onSortModeChange={setSortMode}
          />
        </div>

        {loading && (
          <div className="py-20 text-center">
            <p className="text-sm font-medium text-slate-500">Loading live feed...</p>
          </div>
        )}

        {!loading && feedItems.length === 0 && (
          <div className="py-20 text-center">
            <p className="text-sm font-medium text-slate-500">
              Live feed is warming up. Drop a design into the Google Drive folders and refresh.
            </p>
          </div>
        )}

        {!loading && feedItems.length > 0 && (
          <>
            {/* Desktop split layout */}
            <div className="hidden gap-6 lg:flex">
              {/* Left: Masonry grid */}
              <section className="w-2/3">
                <div className="columns-1 gap-4 sm:columns-2 xl:columns-3">
                  {desktopMasonryItems.map((item) => (
                    <MasonryItemCard
                      key={item.id}
                      item={item}
                      isLatest={item.id === latestItemId}
                      liveStatus={liveStatusLabel}
                      onOpen={setActiveItem}
                      onRegisterView={registerView}
                    />
                  ))}
                </div>
              </section>

              {/* Right: Sticky reels feed - visually distinct with aqua stroke */}
              <aside className="sticky top-24 flex h-[calc(100vh-8rem)] w-1/3 flex-col gap-3 overflow-y-auto rounded-3xl border border-cyan-400/60 bg-gradient-to-b from-slate-900 via-slate-900 to-slate-950/95 p-3 shadow-xl shadow-cyan-500/30">
                <div className="mb-1 flex items-center justify-between px-1">
                  <div>
                    <p className="text-[11px] font-medium uppercase tracking-[0.16em] text-slate-300">
                      Reels & Video Room
                    </p>
                    <p className="text-xs text-slate-400">
                      Vertical-first edits, pinned in a dedicated lane.
                    </p>
                  </div>
                  <span className="inline-flex items-center gap-1 rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-medium text-emerald-200">
                    <span className="relative flex h-2 w-2">
                      <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400/80 opacity-75" />
                      <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-400" />
                    </span>
                    Live lane
                  </span>
                </div>
                <div className="flex flex-1 flex-col gap-3 pb-2">
                  {reels.map((item) => (
                    <ReelCard
                      key={item.id}
                      item={item}
                      isLatest={item.id === latestItemId}
                      onOpen={setActiveItem}
                      onRegisterView={registerView}
                    />
                  ))}
                </div>
              </aside>
            </div>

            {/* Mobile mixed feed */}
            <div className="flex flex-col gap-3 lg:hidden">
              {mobileFeedItems.map((item) => (
                <MobileFeedItem
                  key={item.id}
                  item={item}
                  onOpen={setActiveItem}
                  onRegisterView={registerView}
                />
              ))}
            </div>
          </>
        )}
      </main >

      <FooterCTA />

      {
        activeItem && (
          <ItemModal
            item={activeItem}
            isLatest={activeItem.id === latestItemId}
            liveStatus={liveStatusLabel}
            onClose={() => setActiveItem(null)}
          />
        )
      }
    </div >
  );
}

export default App;
